### PR TITLE
Flat Theme support

### PR DESCRIPTION
**Pull request by daagar**
Add new 'flat theme' option to all miniwindow plugins and main layout to give a "modern" look inspired by Visual Studio Code, Discord, etc.

---
My old-man eyes can no longer take the super high contrast of solid black backgrounds, bright borders, and neon text. After playing around with things, I found what I believe to be a very nice "muted" style that takes its inspiration from Visual Studio Code (and similar) editors. I've attempted to integrate the change in such a way that it could be rolled into the main suite. Each plugin offers a "Flat Theme" menu entry (the main window can be enabled with the alias 'flat_theme'). 

No harm if you don't want to roll this in. I just wanted to ensure I didn't have to keep re-making the same edits after the client updates. 

An example screenshot with the flat theme enabled for all the windows (ascii map not displayed, but shares the same look). This is a custom colorset as well - not completely finalized, but I intend to document those settings as part of the whole "package" 

image

### CODE REVIEW

**Comment by fiendish** [comment]
Thanks. I'll review it soon. I seem to have accidentally deleted a bunch of code changes fixing #240 just before committing them, so I have to redo it all now, and I'll get to this after.

**Comment by daagar** [comment]
No worries. Like I said, this was mostly just for personal preferences so no big deal if it doesn't jive as being something worth adding to the base install.

**Comment by fiendish** [comment]
I like the idea and visual look that you've created. Way back when I was first making these plugins I'd created a theme file format that I then stopped using. But it sounds like it's time to bring that back.

Would you be willing to make this work with the basic themes framework I just committed to development? ( https://github.com/fiendish/aardwolfclientpackage/commit/104e099a1bd7805e99e2eb05fddca6b4b9313e61 and https://github.com/fiendish/aardwolfclientpackage/commit/44f12ca0606cf4e3f3d827a12c4902b670500c6a )

**Comment by fiendish** [comment]
I notice that you haven't logged into Aardwolf (at least not with the similarly named character profile) in a few months. I hope everything is ok. In any event I'm going to leave this open as a reminder to myself to get back to it after the next round of bugs is fixed.

**Comment by daagar** [comment]
Apologies for dropping off the face of the earth. Will try to take a stab at figuring out what I did way back when, and making it work with your framework.

**Comment by daagar** [comment]
It might be helpful if you "converted" one of your plugins to use the theme support. I didn't have any trouble hooking up a menu option to call choose_theme(), and do some minor changes to get some of the options to be recognized but I don't think I'm making use of all the variables correctly (I was just using the ASCII plugin as a base, since it is 'simple' as far as the window components go). For example, I might be using theme.FACE when you intended theme.DETAIL or whatever. 

I also wasn't entire sure how or if you still wanted to use DrawThemed3DRect() and DrawThemedResizeTag() - I was able to make most changes without using them at all, but noticing their presence is what made me realize I'm probably not using theme.FACE/HIGHLIGHT/DETAIL, etc the way it was intended.

**Comment by fiendish** [comment]
That's a good point. I should find a pictorial guide that describes common
ui theming components and follow that for naming.

Themed3D rect is a brute replacement for 3D style rectangles because that
style of rect only draws in greys (or maybe the system theme?). The main
use for them is giving an appearance of depth, like depressable buttons or
thickening the scrollbar slider widget.


On Aug 5, 2017 1:02 PM, "daagar" <notifications@github.com> wrote:

It might be helpful if you "converted" one of your plugins to use the theme
support. I didn't have any trouble hooking up a menu option to call
choose_theme(), and do some minor changes to get some of the options to be
recognized but I don't think I'm making use of all the variables correctly.
For example, I might be using theme.FACE when you intended theme.DETAIL or
whatever.

I also wasn't entire sure how or if you still wanted to use
DrawThemed3DRect() and DrawThemedResizeTag() - I was able to make most
changes without using them at all, but noticing their presence is what made
me realize I'm probably not using theme.FACE/HIGHLIGHT/DETAIL, etc the way
it was intended.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/fiendish/aardwolfclientpackage/pull/243#issuecomment-320455010>,
or mute the thread

**Comment by daagar** [comment]
That would be greatly helpful! It is discoverable somewhat by trial and error (since that's how I did the original PR), but I fear more error than anything else. 

I forgot about the hackish stuff I had to do to get the scrollbars themed nicely, so very cool that the new method helps with that.

**Comment by fiendish** [comment]
Sorry I got waylayed by another project. Working on this now.

**Comment by fiendish** [comment]
I think I'm finally ready to close this. Theme support is added in the development branch now and will be released shortly. Thanks for sticking with us.

**Pull request closed without merging**
