### PR TITLE
Toggle titlebar menu option

### PR DESCRIPTION
**Pull request by Apaxis**
The menu option for toggling of the titlebar is completed. This feature completes the implementation of Level's request to be able to hide the titlebar and was written by Kobus (me).

### CODE REVIEW

**Comment by fiendish** [comment]
Hi, thanks! Can you do your pr against the development branch instead? Sorry about this.

**Comment by fiendish** [comment]
I can also do it for you, but I'm not sure what needs to happen to do that and keep you linked as the commit author on github.

**Comment by fiendish** [comment]
Never mind. I think I did it? 😅

**Comment by Apaxis** [comment]
Hrm, looks like it's going the opposite direction :p

**Comment by Apaxis** [comment]
Ok no that looks right, I think....

**Comment by Apaxis** [comment]
I think I may need to close this and do the pull request on the dev branch either way.

**Comment by Apaxis** [comment]
Or just another pull request, I'm not very good with GIT...

**Comment by Apaxis** [comment]
Ok, nm i've reviewed a bit more thoroughly and I think it's safe to pull/merge now lol

**Comment by fiendish** [comment]
It does look weird now, doesn't it? Maybe close it and redo the pr on dev just to be safe.

**Comment by Apaxis** [comment]
Ok

**Pull request closed without merging**
