### PR TITLE
Add manual full cexit and GUI edit cexit support

### PR DESCRIPTION
**Pull request by davidcw6**

### CODE REVIEW

**Comment by davidcw6** [comment]
Adds mapper fullcexit {\<command\>} \<source room id\> \<destination room id\>
Adds change CExit menu on right click of room which allows you to change command between an existing source/destination cexit

**Comment by fiendish** [comment]
Thanks for the submission. I've been a little busy with the gag/sub plugin, but I'll take a look soon.

**Comment by davidcw6** [comment]
Not a problem. Thanks. I've been testing it for a few days without issues.

**Comment by fiendish** [comment]
Can you tell me about the motivation for wanting this? I don't see the point of storing a cexit that hasn't been tested.

**Comment by davidcw6** [comment]
There are two aspects to this.

The most important is the GUI edit feature as you can edit the command of existing cexit without having to remake. As an example, changing a wait(3) to wait(4). This is the critical aspect that should be extremely relevant to most cexit users.

The other aspect is if you prefer to work out a cexit by thinking through it or running through manually and then just add it directly. For example to build a cexit involving multiple rooms and not just one simple command I will usually build my cexit command one step at a time and then add it all at once once I've tested myself. Having the mapper test just means I have to go back and delete the cexit if I have any errors since the mapper assumes my end room is correct (regardless of it being actually correct). I view this the same as the mapper fullportal command. It gives slightly more flexibility to those that choose to understand how they are moving without having to spend what can sometimes be long times running through a cexit...E.g. what if your cexit had multiple waits and you were just fixing one typo?

**Comment by fiendish** [comment]
done. thank you.

**Pull request closed without merging**
