### PR TITLE
Show/Hide Titlebar

### PR DESCRIPTION
**Pull request by rdutta**
Would like the option to hide the title bar on the ascii map miniwin

### CODE REVIEW

**Comment by fiendish** [comment]
already exists as "Show Room Name" ^_^

**Comment by fiendish** [comment]
But you're right, that should probably also toggle the title bar.

**Review by fiendish — CHANGES_REQUESTED** [review]
If you switch this over to using the existing "Show Room Name" option I'll merge it in.

**Comment by Apaxis** [comment]
This can be done I think.

**Comment by fiendish** [comment]
I mean, I could do it, but I figure rauru could get credit after going this far. I need to look up if it's possible to make a change and assign authorship to someone else. That might be easiest.

**Comment by fiendish** [comment]
b9f1a52dd63a12a33a88c00c72ee053725d7f135

**Pull request closed without merging**
